### ISSUE TITLE
Remove or switch out Firebase-Crashlytics

### ISSUE THREAD

**Issue by gscanlonhq** [gscanlon21/reverse-dictionary#6]
Firebase Crashlytics is preventing the app from being hosted on f-droid. Need to switch that out for a foss alternative or remove crash reporting altogether. Possibly by adding a build-variant for f-droid that excludes that library.

[F-Droid's inclusion policy](https://f-droid.org/docs/Inclusion_Policy/)

**Comment by gscanlon21** [comment]
Fixed with commit 5a3a2cc9 & 5d5c799b
